apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  selector:
    matchLabels:
      app: datanode
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          imagePullPolicy: Always
          name: datanode
          env:
            - name: SERVICE_PRECONDITION
              value: "namenode:9870"
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://namenode:8020"
            - name: CORE_CONF_hadoop_http_staticuser_user
              value: "root"
            - name: CORE_CONF_hadoop_proxyuser_hue_hosts
              value: "*"
            - name: CORE_CONF_hadoop_proxyuser_hue_groups
              value: "*"
            - name: CORE_CONF_io_compression_codecs
              value: "org.apache.hadoop.io.compress.SnappyCodec"
            - name: HDFS_CONF_dfs_webhdfs_enabled
              value: "true"
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
