apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-scanner
  labels:
    app: sonar-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-scanner
  template:
    metadata:
      labels:
        app: sonar-scanner
    spec:
      containers:
      - name: sonar-scanner
        image: newtmitch/sonar-scanner
        command: ["sonar-scanner"]
        args: ["-Dsonar.host.url=http://${SONARQUBE EXTERNAL IP AND PORT}", "-Dsonar.login=${SONARQUBE TOKEN}", "-Dsonar.projectName='Sonar Scanner'"]
