apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  selector:
    matchLabels:
      app: sonar
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - image: sonarqube
          imagePullPolicy: Always
          name: sonar
          ports:
            - containerPort: 9000
